extends Node

var TILESET_TEST

func _ready():
	TILESET_TEST = [preload("res://assets/images/TILESET_TEST/0-0-0.png"),
					preload("res://assets/images/TILESET_TEST/0-0-1.png"),
					preload("res://assets/images/TILESET_TEST/0-0-2.png"),
					preload("res://assets/images/TILESET_TEST/0-0-3.png"),
					preload("res://assets/images/TILESET_TEST/0-0-4.png"),
					preload("res://assets/images/TILESET_TEST/0-0-5.png"),
					preload("res://assets/images/TILESET_TEST/0-0-6.png"),
					preload("res://assets/images/TILESET_TEST/0-0-7.png"),
					preload("res://assets/images/TILESET_TEST/0-0-8.png"),
					preload("res://assets/images/TILESET_TEST/0-0-9.png"),
					preload("res://assets/images/TILESET_TEST/0-0-10.png"),
					preload("res://assets/images/TILESET_TEST/0-0-11.png"),
					preload("res://assets/images/TILESET_TEST/0-0-12.png"),
					preload("res://assets/images/TILESET_TEST/0-0-13.png"),
					preload("res://assets/images/TILESET_TEST/0-0-14.png"),
					preload("res://assets/images/TILESET_TEST/0-0-15.png"),
					preload("res://assets/images/TILESET_TEST/0-0-16.png"),
					preload("res://assets/images/TILESET_TEST/0-0-17.png"),
					preload("res://assets/images/TILESET_TEST/0-0-18.png"),
					preload("res://assets/images/TILESET_TEST/0-0-19.png"),
					preload("res://assets/images/TILESET_TEST/0-0-20.png"),
					preload("res://assets/images/TILESET_TEST/0-0-21.png"),
					preload("res://assets/images/TILESET_TEST/0-0-22.png"),
					preload("res://assets/images/TILESET_TEST/0-0-23.png"),
					preload("res://assets/images/TILESET_TEST/0-0-24.png"),
					preload("res://assets/images/TILESET_TEST/0-0-25.png"),
					preload("res://assets/images/TILESET_TEST/0-0-26.png"),
					preload("res://assets/images/TILESET_TEST/0-0-27.png"),
					preload("res://assets/images/TILESET_TEST/0-0-28.png"),
					preload("res://assets/images/TILESET_TEST/0-0-29.png"),
					preload("res://assets/images/TILESET_TEST/0-0-30.png"),
					preload("res://assets/images/TILESET_TEST/0-0-31.png"),
					preload("res://assets/images/TILESET_TEST/0-0-32.png"),
					preload("res://assets/images/TILESET_TEST/0-0-33.png"),
					preload("res://assets/images/TILESET_TEST/0-0-34.png"),
					preload("res://assets/images/TILESET_TEST/0-0-35.png"),
					preload("res://assets/images/TILESET_TEST/0-0-36.png"),
					preload("res://assets/images/TILESET_TEST/0-0-37.png"),
					preload("res://assets/images/TILESET_TEST/0-0-38.png"),
					preload("res://assets/images/TILESET_TEST/0-0-39.png"),
					preload("res://assets/images/TILESET_TEST/0-0-40.png"),
					preload("res://assets/images/TILESET_TEST/0-0-41.png"),
					preload("res://assets/images/TILESET_TEST/0-0-42.png"),
					preload("res://assets/images/TILESET_TEST/0-0-43.png"),
					preload("res://assets/images/TILESET_TEST/0-0-44.png"),
					preload("res://assets/images/TILESET_TEST/0-0-45.png"),
					preload("res://assets/images/TILESET_TEST/0-0-46.png"),
					preload("res://assets/images/TILESET_TEST/0-0-47.png"),
					preload("res://assets/images/TILESET_TEST/0-0-48.png"),
					preload("res://assets/images/TILESET_TEST/0-0-49.png"),
					preload("res://assets/images/TILESET_TEST/0-0-50.png"),
					preload("res://assets/images/TILESET_TEST/0-0-51.png"),
					preload("res://assets/images/TILESET_TEST/0-0-52.png")]